language: android

android:
    components:
        - build-tools-22.0.1
        - android-22

before_script:
    - export PATH=$PATH:$ANDROID_HOME/build-tools/22.0.1

script:
    - ./gradlew -v
    - ./gradlew plugin:jar testapk:assembleDebug -q
    - ./gradlew plugin:test --stacktrace

